from .offensive_speech_classifier import OffensiveSpeechClassifier as DefaultOffensiveSpeechClassifier

from .offensive_speech_classifier_servicer import Servicer
from .offensive_speech_classifier_servicer import add_SafetyServicer_to_server as add_to_server