theme_recommendations = {
    'dinner': 'thai green curry',
    'lunch':  'grilled cheese sandwich',
    'breakfast': 'fluffy american pancakes',
    'italian': 'creamy pasta with mushrooms (pasta ai funghi)',
    'healthy': 'chicken soba noodles',
    'quick': 'chicken fajita',
    'indian': 'red lentil dal',
    'chinese': 'soy sauce chow mein',
    'asian': 'thai green curry',
    'baking': 'blueberry muffins',
    'salad':  'chicken caesar salad',
    'soup':  'minestrone soup',
    'desserts': 'homemade apple pie',
    'vegan': 'vegan chickpea curry',
    'thanksgiving': 'thanksgiving turkey',
    'pasta': 'chicken pasta bake',
    'pizza': 'pizza bufalina',
    'turkey': 'roast turkey with lemon and garlic',
}
