from .joke_retriever import JokeRetriever as DefaultJokeRetriever

from .joke_retriever_servicer import Servicer
from .joke_retriever_servicer import add_JokeRetrieverServicer_to_server as add_to_server