name = "functionalities"

base_path = "/shared/file_system/downloads/functionalities/"

[[sources]]
id = "extra_info_data_recent"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/misc/extra_info_data/jokes_images.json", "extra_info_data/jokes_images.json"],
]

artefacts = [
    ["jokes_json", "extra_info_data/jokes_images.json"],
]

[[sources]]
id = "system_indexes_objects_idx"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/indexes/system_indexes/objects_idx.zip", "system_indexes/objects_idx.zip"],
]

artefacts = [
    ["objects_idx", "system_indexes/objects_idx"],
]

[[sources]]
id = "system_indexes_search_idx_sparse"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/indexes/system_indexes/search_idx/sparse.zip", "system_indexes/search_idx/sparse.zip"],
]

artefacts = [
    ["sparse_search_idx", "system_indexes/search_idx/sparse"],
]

[[sources]]
id = "system_indexes_search_idx_dense"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/indexes/system_indexes/search_idx/dense.zip", "system_indexes/search_idx/dense.zip"],
]

artefacts = [
    ["dense_search_idx", "system_indexes/search_idx/dense"],
]

[[sources]]
id = "category_index_objects_idx"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/indexes/category_index/objects_idx.zip", "category_index/objects_idx.zip"],
]

artefacts = [
    ["category_idx", "category_index/objects_idx"],
]

[[sources]]
id = "tags"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/misc/tags/tag_counts.json", "tags/tag_counts.json"],
]

artefacts = [
    ["tag_counts", "tags/tag_counts.json"],
]

# models
[[sources]]
id = "domain_classifier"
urls = [
    ["https://oat-2-data.s3.amazonaws.com/classifiers/domain_classifier/domain_list.json", "domain_classifier/domain_list.json"],
    ["https://oat-2-data.s3.amazonaws.com/classifiers/domain_classifier/id_to_domain.json", "domain_classifier/id_to_domain.json"],
    ["https://oat-2-data.s3.amazonaws.com/classifiers/domain_classifier/naive_bayes.pkl", "domain_classifier/naive_bayes.pkl"],
    ["https://oat-2-data.s3.amazonaws.com/classifiers/domain_classifier/tfidf.pkl", "domain_classifier/tfidf.pkl"],
]

artefacts = [
    ["domain_classifier", "domain_classifier"],
]
