apiVersion: apps/v1
kind: Deployment
metadata:
  name: functionalities
#  namespace: develop
spec:
  selector:
    matchLabels:
      grill_app: functionalities
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        grill_app: functionalities
    spec:
      containers:
      - name: functionalities
        imagePullPolicy: Always # makes sure to pull from the local docker registry
        image: 103324463696.dkr.ecr.us-east-1.amazonaws.com/alexa_oat-functionalities:latest
        ports:
          - containerPort: 8000
        workingDir: /source # the directory to go to when ssh'ing in
        env:
          - name: CONTAINER_NAME
            value: "functionalities"
          - name: EXTERNAL_FUNCTIONALITIES_URL
            value: "external-functionalities:8000"
          - name: FUNCTIONALITIES_URL
            value: "localhost:8000"
          - name: NEURAL_FUNCTIONALITIES_URL
            value: "neural-functionalities:8000"
          - name: USE_ASR
            value: "TRUE"
          - name: LLM_FUNCTIONALITIES_URL
            value: "llm-functionalities:8000"
      nodeSelector:
        node_type: cpu
---
apiVersion: v1
kind: Service
metadata:
  name: functionalities
#  namespace: develop
  labels:
    grill_app: functionalities-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    grill_app: functionalities
  type: LoadBalancer