apiVersion: apps/v1
kind: Deployment
metadata:
  name: neural-functionalities
#  namespace: develop
spec:
  selector:
    matchLabels:
      grill_app: neural-functionalities
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        grill_app: neural-functionalities
    spec:
      containers:
      - name: neural-functionalities
        imagePullPolicy: Always # makes sure to pull from the local docker registry
        image: 103324463696.dkr.ecr.us-east-1.amazonaws.com/alexa_oat-neural_functionalities:latest
        ports:
          - containerPort: 8000
        workingDir: /source # the directory to go to when ssh'ing in
        env:
          - name: CONTAINER_NAME
            value: "neural_functionalities"
          - name: EXTERNAL_FUNCTIONALITIES_URL
            value: "external-functionalities:8000"
          - name: FUNCTIONALITIES_URL
            value: "localhost:8000"
          - name: NEURAL_FUNCTIONALITIES_URL
            value: "neural-functionalities:8000"
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
      nodeSelector:
        node_type: gpu
---
apiVersion: v1
kind: Service
metadata:
  name: neural-functionalities
#  namespace: develop
  labels:
    grill_app: neural-functionalities-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    grill_app: neural-functionalities
  type: LoadBalancer