apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
#  namespace: develop
spec:
  selector:
    matchLabels:
      grill_app: orchestrator
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        grill_app: orchestrator
    spec:
      containers:
      - name: orchestrator
        imagePullPolicy: Always # makes sure to pull from the local docker registry
        image: 103324463696.dkr.ecr.us-east-1.amazonaws.com/alexa_oat-orchestrator:latest
        ports:
          - containerPort: 8000
        workingDir: /source # the directory to go to when ssh'ing in
        env:
          - name: CONTAINER_NAME
            value: "orchestrator"
          - name: FUNCTIONALITIES_URL
            value: "functionalities:8000"
          - name: EXTERNAL_FUNCTIONALITIES_URL
            value: "external-functionalities:8000"
          - name: NEURAL_FUNCTIONALITIES_URL
            value: "neural-functionalities:8000"
          - name: LLM_FUNCTIONALITIES_URL
            value: "llm-functionalities:8000"
      nodeSelector:
        node_type: orchestrator_cpu_bigger
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
#  namespace: develop
  labels:
    grill_app: orchestrator-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    grill_app: orchestrator
  type: LoadBalancer