apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmap-generation
#  namespace: develop
spec:
  selector:
    matchLabels:
      grill_app: taskmap-generation
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        grill_app: taskmap-generation
    spec:
      containers:
      - name: taskmap-generation
        imagePullPolicy: Never # makes sure to pull from the local docker registry
        image: taskmap_generation:latest
        command:
          - 'jupyter-lab'
        args:
          - '--no-browser'
          - '--ip=0.0.0.0'
          - '--allow-root'
          - '--NotebookApp.token='
          - '--notebook-dir="/source/"'
        ports:
        - containerPort: 8888
        volumeMounts:
          - mountPath: /shared/file_system  # this takes the volume name defined bellow and mounts it in the pod
            name: persistent-storage
        env:
          - name: CONTAINER_NAME
            value: "taskmap-generation"
      volumes:
        - name: persistent-storage # this is taking the file system from minikube and giving it a volume name
          hostPath:
            path: /shared/file_system # this is actually in the minikube vm

---
apiVersion: v1
kind: Service
metadata:
  name: taskmap-generation
#  namespace: develop
  labels:
    grill_app: taskmap-generation-service
spec:
  ports:
  - port: 7777
    targetPort: 8888
  selector:
    grill_app: taskmap-generation
  type: LoadBalancer