version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  full:
    format: "[%(asctime)s] - %(levelname)s - %(name)s - %(funcName)s:%(lineno)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: full
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: full
    filename: /shared/file_system/logs/db.log
    maxBytes: 100000000
    backupCount: 3
  watchtower:
    class: watchtower.CloudWatchLogHandler
    formatter: full
    level: DEBUG
    log_group: watchtower
    stream_name: "{logger_name}"
    send_interval: 10
    create_log_group: False
loggers:
  local:
    level: INFO
    handlers: [console, file]
    propagate: no
  cloud:
    level: DEBUG
    handlers: [console,file,watchtower]
    propagate: no
root:
  level: INFO
  handlers: [console,file]