name = "offline"
enabled = true
base_path = "shared/file_system/downloads/offline/"
[[sources]]
# missing id = line here
urls = [
     "s3://...",
    "https://...",
]
enabled = true
local_path = "example/source/files"
force = false
